name: Deploy to Azure - Dev Mode

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: aiandrew631/ascend-avoid
  AZURE_CONTAINER_APP: ascend-avoid
  AZURE_RESOURCE_GROUP: ascend-avoid-rg

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name ${{ env.AZURE_CONTAINER_APP }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --image ${{ env.IMAGE_NAME }}:latest \
          --set-env-vars "NODE_ENV=production" "PORT=3000"
        
        # Update ingress configuration separately
        az containerapp ingress update \
          --name ${{ env.AZURE_CONTAINER_APP }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --target-port 5173
    
    - name: Verify deployment
      run: |
        echo "🚀 Deployment complete!"
        echo "📱 App URL: https://${{ env.AZURE_CONTAINER_APP }}.azurecontainerapps.io"
        echo "🌐 Custom domain: https://ascend.drewclark.io"
        echo "🔧 Running in dev mode with Vite + Express"
